[tool.poetry]
name = "exposer"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
temporalio = "^1.3.0"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"

[tool.poetry.scripts]
worker = "exposer.worker:main"
workflow = "exposer.run_workflow:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
